/* Lógico_1: */
/*DROP DATABASE MUSEU;*/
CREATE DATABASE MUSEU;
USE MUSEU;

CREATE TABLE INSTITUICAO_RESPONSAVEL (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT, 
    INSTITUICAO varchar(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TIPO_ORGANIZACAO VARCHAR(255) NOT NULL,
    CEP VARCHAR(20) NOT NULL,
    RUA VARCHAR(255) NOT NULL,
    NUMERO INTEGER NOT NULL,
    BAIRRO VARCHAR(255) NOT NULL,
    CIDADE VARCHAR(255) NOT NULL,
    UF CHAR(2) NOT NULL,
    DT_CAD DATE NOT NULL,
    OCUPACAO VARCHAR(100),
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(20),
    SESSAO VARCHAR(255)
);

CREATE TABLE AGENDA (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    DATA DATE NOT NULL,
    NUM_VISITANTES INTEGER NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    N_ESPECIAL VARCHAR(5),
    DESCRICAO_NECESSIDADE_ESPECIAL VARCHAR(255),
    FK_INSTITUICAO_RESPONSAVEL_ID INTEGER,
    MOTIVO_STATUS VARCHAR(255),
    HORA TIME
);

CREATE TABLE TIPO_NECESSIDADE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    TIPO VARCHAR(20) NOT NULL
);

CREATE TABLE USUARIO (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE VISITANTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255),
    OCUPACAO VARCHAR(100),
    DT_NASCIMENTO DATE,
    CIDADE VARCHAR(255),
    UF CHAR(2),
    MENSAGEM VARCHAR(255),
    DT_CAD DATE
);


CREATE TABLE CLASSIFICA_TIPO (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    FK_AGENDA_ID INTEGER,
    FK_TIPO_NECESSIDADE_ID INTEGER
);
 
ALTER TABLE AGENDA ADD CONSTRAINT FK_AGENDA_2
    FOREIGN KEY (FK_INSTITUICAO_RESPONSAVEL_ID)
    REFERENCES INSTITUICAO_RESPONSAVEL (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE;
 
 
ALTER TABLE CLASSIFICA_TIPO ADD CONSTRAINT FK_CLASSIFICA_TIPO_2
    FOREIGN KEY (FK_AGENDA_ID)
    REFERENCES AGENDA (ID);
 
ALTER TABLE CLASSIFICA_TIPO ADD CONSTRAINT FK_CLASSIFICA_TIPO_3
    FOREIGN KEY (FK_TIPO_NECESSIDADE_ID)
    REFERENCES TIPO_NECESSIDADE (ID);